parameters:
  sylius_prediction_event_host: 127.0.0.1
  sylius_prediction_event_port: 7070
  sylius_prediction_engine_host: 127.0.0.1
  sylius_prediction_engine_port: 8192
  sylius_prediction_key: ''

services:
    sylius_personalized_products.factory.connect:
        class: cv65kr\SyliusPersonalizedProducts\Factory\PredictionConnectFactory
        arguments:
          - "%sylius_prediction_event_host%"
          - "%sylius_prediction_event_port%"
          - "%sylius_prediction_engine_host%"
          - "%sylius_prediction_engine_port%"
          - "%sylius_prediction_key%"

    sylius_personalized_products.services.populate_products:
        class: cv65kr\SyliusPersonalizedProducts\Services\PopulateProducts
        arguments:
          - "@sylius_personalized_products.factory.connect"
          - "@sylius.repository.product"

    sylius_personalized_products.services.populate_customers:
        class: cv65kr\SyliusPersonalizedProducts\Services\PopulateCustomers
        arguments:
          - "@sylius_personalized_products.factory.connect"
          - "@sylius.repository.customer"

    sylius_personalized_products.command.populate_command:
        class: cv65kr\SyliusPersonalizedProducts\Command\PopulateCommand
        arguments:
          - "@sylius_personalized_products.services.populate_products"
          - "@sylius_personalized_products.services.populate_customers"
        tags:
          - { name: "console.command" }

    sylius_personalized_products.event_listener.product_listener:
        class: cv65kr\SyliusPersonalizedProducts\EventListener\ProductListener
        arguments:
          - "@sylius.context.customer"
          - "@sylius_personalized_products.factory.connect"
          - "@sylius_personalized_products.services.populate_products"
        tags:
            -  { name: kernel.event_listener, event: sylius.product.show, method: onProductShow }
            -  { name: kernel.event_listener, event: sylius.product.post_create, method: onProductCreate }
            -  { name: kernel.event_listener, event: sylius.product.post_update, method: onProductUpdate }
            -  { name: kernel.event_listener, event: sylius.product.pre_delete, method: onProductRemove }

    sylius_personalized_products.controller.personalized_products_controller:
        class: cv65kr\SyliusPersonalizedProducts\Controller\PersonalizedProductsController
        arguments:
          - "@sylius.context.customer"
          - "@sylius_personalized_products.factory.connect"
          - "@templating"
          - "@sylius_personalized_products.transformer.product_transformer"

    sylius_personalized_products.transformer.product_transformer:
        class: cv65kr\SyliusPersonalizedProducts\Transformer\ProductTransformer
        arguments:
          - "@sylius.repository.product"